// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoHub.Database;

#nullable disable

namespace ProtoHub.Database.Migrations
{
    [DbContext(typeof(ProtoHubDbContext))]
    [Migration("20260407073220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoHub.Database.Models.MenuGroupModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<string>("icon")
                        .HasColumnType("text")
                        .HasComment("图标");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("分组名称");

                    b.Property<int>("order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("排序");

                    b.Property<DateTime>("update_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("更新时间");

                    b.HasKey("id");

                    b.HasIndex("order")
                        .HasDatabaseName("idx_menu_group_order");

                    b.ToTable("t_menu_group", "protohub", t =>
                        {
                            t.HasComment("菜单分组表（项目表）");
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.MenuItemModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<string>("doc_description")
                        .HasColumnType("text")
                        .HasComment("文档描述");

                    b.Property<string>("doc_file_id")
                        .HasColumnType("text")
                        .HasComment("文档文件ID");

                    b.Property<string>("doc_file_name")
                        .HasColumnType("text")
                        .HasComment("文档文件名");

                    b.Property<long>("group_id")
                        .HasColumnType("bigint")
                        .HasComment("所属分组ID");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("菜单名称");

                    b.Property<int>("order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("排序");

                    b.Property<string>("route")
                        .HasColumnType("text")
                        .HasComment("内部路由");

                    b.Property<string>("type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("web")
                        .HasComment("类型（web/miniprogram/doc/link/internal）");

                    b.Property<DateTime>("update_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("更新时间");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasComment("链接地址");

                    b.Property<string>("viewport_config")
                        .HasColumnType("jsonb")
                        .HasComment("视口配置");

                    b.HasKey("id");

                    b.HasIndex("group_id")
                        .HasDatabaseName("idx_menu_item_group_id");

                    b.HasIndex("group_id", "order")
                        .HasDatabaseName("idx_menu_item_group_order");

                    b.ToTable("t_menu_item", "protohub", t =>
                        {
                            t.HasComment("菜单项表（项目子项表）");
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.PermissionModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasComment("分类");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("权限编码");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("权限名称");

                    b.HasKey("id");

                    b.HasIndex("category")
                        .HasDatabaseName("idx_permission_category");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("idx_permission_code");

                    b.ToTable("t_permission", "protohub", t =>
                        {
                            t.HasComment("权限表");
                        });

                    b.HasData(
                        new
                        {
                            id = 1L,
                            category = "系统",
                            code = "dashboard",
                            description = "访问仪表板",
                            name = "仪表板"
                        },
                        new
                        {
                            id = 2L,
                            category = "系统",
                            code = "settings",
                            description = "系统设置管理",
                            name = "系统设置"
                        },
                        new
                        {
                            id = 3L,
                            category = "系统",
                            code = "user-manage:view",
                            description = "查看用户列表",
                            name = "查看用户"
                        },
                        new
                        {
                            id = 4L,
                            category = "系统",
                            code = "user-manage:create",
                            description = "创建新用户",
                            name = "创建用户"
                        },
                        new
                        {
                            id = 5L,
                            category = "系统",
                            code = "user-manage:update",
                            description = "编辑用户信息",
                            name = "编辑用户"
                        },
                        new
                        {
                            id = 6L,
                            category = "系统",
                            code = "user-manage:delete",
                            description = "删除用户",
                            name = "删除用户"
                        },
                        new
                        {
                            id = 7L,
                            category = "系统",
                            code = "user-manage:assign-role",
                            description = "为用户分配角色",
                            name = "分配用户角色"
                        },
                        new
                        {
                            id = 8L,
                            category = "系统",
                            code = "role-manage:view",
                            description = "查看角色列表",
                            name = "查看角色"
                        },
                        new
                        {
                            id = 9L,
                            category = "系统",
                            code = "role-manage:create",
                            description = "创建新角色",
                            name = "创建角色"
                        },
                        new
                        {
                            id = 10L,
                            category = "系统",
                            code = "role-manage:update",
                            description = "编辑角色信息",
                            name = "编辑角色"
                        },
                        new
                        {
                            id = 11L,
                            category = "系统",
                            code = "role-manage:delete",
                            description = "删除角色",
                            name = "删除角色"
                        },
                        new
                        {
                            id = 12L,
                            category = "系统",
                            code = "role-manage:assign-permission",
                            description = "为角色分配权限",
                            name = "分配角色权限"
                        },
                        new
                        {
                            id = 13L,
                            category = "系统",
                            code = "permission-manage:view",
                            description = "查看权限列表",
                            name = "查看权限"
                        },
                        new
                        {
                            id = 14L,
                            category = "系统",
                            code = "system-menu-manage:view",
                            description = "查看系统菜单列表",
                            name = "查看系统菜单"
                        },
                        new
                        {
                            id = 15L,
                            category = "系统",
                            code = "system-menu-manage:create",
                            description = "创建系统菜单",
                            name = "创建系统菜单"
                        },
                        new
                        {
                            id = 16L,
                            category = "系统",
                            code = "system-menu-manage:update",
                            description = "编辑系统菜单",
                            name = "编辑系统菜单"
                        },
                        new
                        {
                            id = 17L,
                            category = "系统",
                            code = "system-menu-manage:delete",
                            description = "删除系统菜单",
                            name = "删除系统菜单"
                        },
                        new
                        {
                            id = 20L,
                            category = "项目",
                            code = "projects:view",
                            description = "查看项目管理列表",
                            name = "查看项目列表"
                        },
                        new
                        {
                            id = 21L,
                            category = "项目",
                            code = "projects:create",
                            description = "创建新项目",
                            name = "创建项目"
                        },
                        new
                        {
                            id = 22L,
                            category = "项目",
                            code = "projects:update",
                            description = "编辑项目信息",
                            name = "编辑项目"
                        },
                        new
                        {
                            id = 23L,
                            category = "项目",
                            code = "projects:delete",
                            description = "删除项目",
                            name = "删除项目"
                        },
                        new
                        {
                            id = 24L,
                            category = "项目",
                            code = "projects:manage-item",
                            description = "管理项目菜单项",
                            name = "管理菜单项"
                        },
                        new
                        {
                            id = 28L,
                            category = "项目",
                            code = "projects:view-all",
                            description = "查看所有项目（不论是否是项目成员）",
                            name = "查看全部项目"
                        },
                        new
                        {
                            id = 25L,
                            category = "项目",
                            code = "project-access:view",
                            description = "查看项目成员列表",
                            name = "查看项目成员"
                        },
                        new
                        {
                            id = 26L,
                            category = "项目",
                            code = "project-access:grant",
                            description = "授权用户项目访问",
                            name = "授权项目访问"
                        },
                        new
                        {
                            id = 27L,
                            category = "项目",
                            code = "project-access:revoke",
                            description = "撤销用户项目访问",
                            name = "撤销项目访问"
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.RoleModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("角色编码");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<bool>("is_system")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("是否系统内置");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("角色名称");

                    b.Property<DateTime>("update_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("更新时间");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("idx_role_code");

                    b.ToTable("t_role", "protohub", t =>
                        {
                            t.HasComment("角色表");
                        });

                    b.HasData(
                        new
                        {
                            id = 1L,
                            code = "admin",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "拥有系统所有权限",
                            is_system = true,
                            name = "系统管理员",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2L,
                            code = "guest",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "只读权限",
                            is_system = true,
                            name = "访客",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.RolePermissionModel", b =>
                {
                    b.Property<long>("role_id")
                        .HasColumnType("bigint")
                        .HasComment("角色ID");

                    b.Property<long>("permission_id")
                        .HasColumnType("bigint")
                        .HasComment("权限ID");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.HasKey("role_id", "permission_id");

                    b.HasIndex("permission_id")
                        .HasDatabaseName("idx_role_permission_permission_id");

                    b.ToTable("t_role_permission", "protohub", t =>
                        {
                            t.HasComment("角色权限关联表");
                        });

                    b.HasData(
                        new
                        {
                            role_id = 1L,
                            permission_id = 1L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 2L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 3L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 4L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 5L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 6L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 7L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 8L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 9L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 10L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 11L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 12L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 13L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 14L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 15L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 16L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 17L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 20L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 21L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 22L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 23L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 24L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 25L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 26L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 27L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            permission_id = 28L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 2L,
                            permission_id = 1L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.RoleSystemMenuModel", b =>
                {
                    b.Property<long>("role_id")
                        .HasColumnType("bigint")
                        .HasComment("角色ID");

                    b.Property<long>("system_menu_id")
                        .HasColumnType("bigint")
                        .HasComment("系统菜单ID");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.HasKey("role_id", "system_menu_id");

                    b.HasIndex("system_menu_id")
                        .HasDatabaseName("idx_role_system_menu_menu_id");

                    b.ToTable("t_role_system_menu", "protohub", t =>
                        {
                            t.HasComment("角色系统菜单关联表");
                        });

                    b.HasData(
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 1L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 2L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 3L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 4L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 5L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 10L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 11L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            role_id = 1L,
                            system_menu_id = 12L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.SystemMenuModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("菜单编码");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<string>("icon")
                        .HasColumnType("text")
                        .HasComment("图标");

                    b.Property<bool>("is_visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("是否可见");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("菜单名称");

                    b.Property<int>("order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("排序");

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint")
                        .HasComment("父菜单ID（支持多级）");

                    b.Property<string>("path")
                        .HasColumnType("text")
                        .HasComment("路由路径");

                    b.Property<string>("permission")
                        .HasColumnType("text")
                        .HasComment("所需权限");

                    b.Property<DateTime>("update_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("更新时间");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("idx_system_menu_code");

                    b.HasIndex("parent_id")
                        .HasDatabaseName("idx_system_menu_parent_id");

                    b.ToTable("t_system_menu", "protohub", t =>
                        {
                            t.HasComment("系统功能菜单表");
                        });

                    b.HasData(
                        new
                        {
                            id = 1L,
                            code = "system",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "setting",
                            is_visible = true,
                            name = "系统管理",
                            order = 100,
                            path = "/system",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2L,
                            code = "user-manage",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "user",
                            is_visible = true,
                            name = "用户管理",
                            order = 1,
                            parent_id = 1L,
                            path = "/system/user",
                            permission = "user-manage:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3L,
                            code = "role-manage",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "team",
                            is_visible = true,
                            name = "角色管理",
                            order = 2,
                            parent_id = 1L,
                            path = "/system/role",
                            permission = "role-manage:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 4L,
                            code = "permission-manage",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "lock",
                            is_visible = true,
                            name = "权限管理",
                            order = 3,
                            parent_id = 1L,
                            path = "/system/permission",
                            permission = "permission-manage:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 5L,
                            code = "system-menu-manage",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "menu",
                            is_visible = true,
                            name = "系统菜单",
                            order = 4,
                            parent_id = 1L,
                            path = "/system/menu",
                            permission = "system-menu-manage:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 10L,
                            code = "project",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "project",
                            is_visible = true,
                            name = "项目管理",
                            order = 200,
                            path = "/project",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 11L,
                            code = "project-list",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "appstore",
                            is_visible = true,
                            name = "项目列表",
                            order = 1,
                            parent_id = 10L,
                            path = "/project/list",
                            permission = "projects:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 12L,
                            code = "project-access",
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            icon = "team",
                            is_visible = true,
                            name = "项目成员",
                            order = 2,
                            parent_id = 10L,
                            path = "/project/access",
                            permission = "project-access:view",
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.UserModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasComment("描述");

                    b.Property<string>("email")
                        .HasColumnType("text")
                        .HasComment("邮箱");

                    b.Property<string>("nick_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("昵称");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("密码");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasComment("状态（0=禁用, 1=启用）");

                    b.Property<DateTime>("update_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("更新时间");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("用户名");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .HasDatabaseName("idx_user_email");

                    b.HasIndex("user_name")
                        .IsUnique()
                        .HasDatabaseName("idx_user_name");

                    b.ToTable("t_user", "protohub", t =>
                        {
                            t.HasComment("用户表");
                        });

                    b.HasData(
                        new
                        {
                            id = 1L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "系统默认管理员",
                            email = "admin@protohub.com",
                            nick_name = "管理员",
                            password = "$2a$12$7ag2WeNZaLTotEEw/kyDF.4Qw1rPXXDtvYtzZlenMN0i49L5gKSAu",
                            status = 1,
                            update_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            user_name = "admin"
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.UserProjectAccessModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("access_type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("view")
                        .HasComment("访问类型（view=查看, manage=管理）");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.Property<long>("granted_by")
                        .HasColumnType("bigint")
                        .HasComment("授权人ID");

                    b.Property<long>("project_id")
                        .HasColumnType("bigint")
                        .HasComment("项目ID（关联t_menu_group.id）");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasComment("用户ID");

                    b.HasKey("id");

                    b.HasIndex("project_id")
                        .HasDatabaseName("idx_user_project_access_project_id");

                    b.HasIndex("user_id")
                        .HasDatabaseName("idx_user_project_access_user_id");

                    b.HasIndex("user_id", "project_id")
                        .IsUnique()
                        .HasDatabaseName("idx_user_project_access_unique");

                    b.ToTable("t_user_project_access", "protohub", t =>
                        {
                            t.HasComment("用户项目访问表");
                        });
                });

            modelBuilder.Entity("ProtoHub.Database.Models.UserRoleModel", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasComment("用户ID");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint")
                        .HasComment("角色ID");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("创建时间");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id")
                        .HasDatabaseName("idx_user_role_role_id");

                    b.ToTable("t_user_role", "protohub", t =>
                        {
                            t.HasComment("用户角色关联表");
                        });

                    b.HasData(
                        new
                        {
                            user_id = 1L,
                            role_id = 1L,
                            create_time = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
