// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThirdNet.Core.AspNetCore;

#nullable disable

namespace ProtoHub.Identity.API.Data.Migrations.ThirdNetDb
{
    [DbContext(typeof(ThirdNetDbContext))]
    [Migration("20250919085714_InitialCreate01")]
    partial class InitialCreate01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ActionList", b =>
                {
                    b.Property<string>("Domain")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("domain")
                        .HasComment("服务程序名");

                    b.Property<string>("Controller")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("controller")
                        .HasComment("控制器名");

                    b.Property<string>("Action")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("action")
                        .HasComment("方法名");

                    b.Property<string>("Methord")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("methord")
                        .HasComment("http方法");

                    b.Property<string>("Path")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasComment("请求路径");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.HasKey("Domain", "Controller", "Action");

                    b.ToTable("t_actionlist", null, t =>
                        {
                            t.HasComment("服务方法表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ApplicationAuthority", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("rolename")
                        .HasComment("角色名");

                    b.Property<string>("Application")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用名");

                    b.HasKey("RoleName", "Application");

                    b.HasIndex("Application");

                    b.ToTable("t_applicationauthority", null, t =>
                        {
                            t.HasComment("应用对应角色表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ApplicationInfo", b =>
                {
                    b.Property<string>("Application")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用标识");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration")
                        .HasComment("有效期");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("iv")
                        .HasComment("加密iv");

                    b.Property<string>("Key")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("key")
                        .HasComment("加密密钥");

                    b.Property<string>("MinVersion")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("minversion")
                        .HasComment("最小版本号");

                    b.Property<string>("Prekey")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("prekey")
                        .HasComment("加密前缀");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("添加时间");

                    b.Property<string>("Url")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasComment("应用地址");

                    b.Property<string>("Version")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("version")
                        .HasComment("当前版本号");

                    b.HasKey("Application");

                    b.ToTable("t_applicationinfo", null, t =>
                        {
                            t.HasComment("应用配置表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ApplicationUpdateList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("自增编号");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用标识");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message")
                        .HasComment("更新内容");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasComment("更新序号");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("添加时间");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("t_application_updatelist", null, t =>
                        {
                            t.HasComment("应用更新日志列表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.IpBlackList", b =>
                {
                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip")
                        .HasComment("黑名单ip");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration")
                        .HasComment("黑名单持续时间，单位小时。");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("开始时间");

                    b.HasKey("Ip");

                    b.ToTable("t_ipblacklist", null, t =>
                        {
                            t.HasComment("ip黑名单");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.IpWhiteList", b =>
                {
                    b.Property<string>("Application")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用标识");

                    b.Property<string>("Ip")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ip")
                        .HasComment("ip地址");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("添加时间");

                    b.HasKey("Application", "Ip");

                    b.ToTable("t_ipwhitelist", null, t =>
                        {
                            t.HasComment("应用白名单");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.RolesAuthority", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("rolename")
                        .HasComment("角色名");

                    b.Property<string>("Domain")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("domain")
                        .HasComment("服务程序名");

                    b.Property<string>("Controller")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("controller")
                        .HasComment("控制器名");

                    b.Property<string>("Action")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("action")
                        .HasComment("方法名");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.HasKey("RoleName", "Domain", "Controller", "Action");

                    b.ToTable("t_roles_authority", null, t =>
                        {
                            t.HasComment("角色权限表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.RolesInfo", b =>
                {
                    b.Property<string>("RoleName")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("rolename")
                        .HasComment("角色名");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("备注信息");

                    b.HasKey("RoleName");

                    b.ToTable("t_rolesinfo", null, t =>
                        {
                            t.HasComment("角色表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.VisitLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("自增编号");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("action")
                        .HasComment("方法名");

                    b.Property<string>("Application")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用标识");

                    b.Property<string>("Auth")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("auth")
                        .HasComment("认证头信息");

                    b.Property<string>("Controller")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("controller")
                        .HasComment("控制器名");

                    b.Property<string>("Domain")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("domain")
                        .HasComment("服务程序名");

                    b.Property<int>("Elapsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("elapsed")
                        .HasComment("请求耗时");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ip")
                        .HasComment("请求ip");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("statuscode")
                        .HasComment("状态码");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("时间");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasComment("请求url");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("useragent")
                        .HasComment("ua信息");

                    b.Property<string>("UserName")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("username")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("t_visitlog", null, t =>
                        {
                            t.HasComment("访问日志表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.VisitLogHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("自增编号");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("action")
                        .HasComment("方法名");

                    b.Property<string>("Application")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("application")
                        .HasComment("应用标识");

                    b.Property<string>("Auth")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("auth")
                        .HasComment("认证头信息");

                    b.Property<string>("Controller")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("controller")
                        .HasComment("控制器名");

                    b.Property<string>("Domain")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("domain")
                        .HasComment("服务程序名");

                    b.Property<int>("Elapsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("elapsed")
                        .HasComment("请求耗时");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ip")
                        .HasComment("请求ip");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("statuscode")
                        .HasComment("状态码");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time")
                        .HasComment("时间");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasComment("请求url");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("useragent")
                        .HasComment("ua信息");

                    b.Property<string>("UserName")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("username")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("t_visitloghistory", null, t =>
                        {
                            t.HasComment("访问日志历史表");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.Common.BackgroundLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("编号");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("addtime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("任务执行时间");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("任务名");

                    b.Property<string>("remark")
                        .HasColumnType("text")
                        .HasComment("备注");

                    b.Property<string>("service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("当前服务名");

                    b.Property<int>("state")
                        .HasColumnType("integer")
                        .HasComment("执行状态：1：成功，9：失败。");

                    b.HasKey("id");

                    b.ToTable("t_background_job_log", null, t =>
                        {
                            t.HasComment("后台任务日志");
                        });
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ApplicationAuthority", b =>
                {
                    b.HasOne("ThirdNet.Core.AspNetCore.ApplicationInfo", "ApplicationConfiguration")
                        .WithMany("RolesList")
                        .HasForeignKey("Application")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_role");

                    b.HasOne("ThirdNet.Core.AspNetCore.RolesInfo", "RolesInfo")
                        .WithMany("ApplicationList")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_authority");

                    b.Navigation("ApplicationConfiguration");

                    b.Navigation("RolesInfo");
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.IpWhiteList", b =>
                {
                    b.HasOne("ThirdNet.Core.AspNetCore.ApplicationInfo", "App")
                        .WithMany("WhiteList")
                        .HasForeignKey("Application")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_whitelist");

                    b.Navigation("App");
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.RolesAuthority", b =>
                {
                    b.HasOne("ThirdNet.Core.AspNetCore.RolesInfo", "RolesInfo")
                        .WithMany("AuthList")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rolesauthority_name");

                    b.Navigation("RolesInfo");
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.ApplicationInfo", b =>
                {
                    b.Navigation("RolesList");

                    b.Navigation("WhiteList");
                });

            modelBuilder.Entity("ThirdNet.Core.AspNetCore.RolesInfo", b =>
                {
                    b.Navigation("ApplicationList");

                    b.Navigation("AuthList");
                });
#pragma warning restore 612, 618
        }
    }
}
